Force node-fetch to 2.0.0
The 2.1.* have a problem when the HTTP Host header is explicitly set:

    Update from API failed TypeError: hostHeader.replace is not a function
        at Agent.addRequest (_http_agent.js:155:39)
        at new ClientRequest (_http_client.js:272:16)
        at request (http.js:39:10)
        at /home/arizen/arizen/node_modules/node-fetch/lib/index.js:1356:15
        at Promise (<anonymous>)
        at fetch (/home/arizen/arizen/node_modules/node-fetch/lib/index.js:1343:9)
        at fetchJson (/home/arizen/arizen/app/main.js:577:24)
        at fetchApi (/home/arizen/arizen/app/main.js:588:16)
        at fetchBlockchainChanges (/home/arizen/arizen/app/main.js:678:28)
        at updateBlockchainView (/home/arizen/arizen/app/main.js:703:24)